project:
  type: website
  output-dir: docs
  
website:
  title: "Leah Levensailor"
  navbar:
    right:
      - text: "Home"
        href: index.html
      - text: "Projects"
        menu: 
          - text: "Air Pollution"
            href: mapping.qmd
          - text: "College Demographics"
            href: scorecard_analysis.qmd
          - text: "World Cube Association"
            href: WCA_analysis.qmd
format:
  html:
    theme: [sandstone, _variables.scss]
    css: styles.css
page-footer:
    right: "Built with [Quarto](https://quarto.org/)"
    left: "&copy; Copyright 2026, Leah Levensailor"

editor: source

