project:
  type: website
  output-dir: docs
  
website:
  title: "Leah Levensailor"
  navbar:
    left:
      - text: "Home"
        href: index.html
      - text: "Portfolio"
        menu: 
            - text: "Air Pollution"
              href: mapping.qmd
            - text: "College Demographics"
              href: scorecard_analysis.qmd
            - text: "World Cube Association"
              href: WCA_analysis.qmd
      - text: "Case Studies"
        menu: 
          - text: "Voter Mistakes"
            href: CaseStudy1.qmd
          - text: "Racial Inequality"
            href: CaseStudy2.qmd
format:
  html:
    theme: sandstone, _variables.scss
    css: styles.css
page-footer:
    right: "Built with [Quarto](https://quarto.org/)"
    left: "&copy; Copyright 2026, Leah Levensailor"

editor: source

